Satle anshul
pcube0608/batch6 pull request #28
Opened 2023-05-05 13:11 UTC by Anshulsatle

Hello Team,

It is a Basket Automation Code

Please Review

2023-05-05 17:17 UTC, komalkapde approved these changes

2023-05-07 05:13 UTC, shriram3672 approved these changes
LGTM

2023-05-07 11:05 UTC, shriram3672 approved these changes

2023-05-07 11:05 UTC, shriram3672 commented on Anshul/IPL1.py
> +
if is it possible to delete below additional lines

2023-05-07 12:27 UTC, komalkapde requested changes

2023-05-07 12:27 UTC, komalkapde commented on Anshul1/Basket.py
> +time.sleep(2)
please remove hardcode wait

2023-05-13 14:52 UTC, ASDESHMUKH approved these changes

2023-05-18 04:16 UTC, closed without merging