Robot_Framework_Goibibo.com
pcube0608/batch6 pull request #35
Opened 2023-05-12 12:40 UTC by Subhajit908

Hi All,

Please review my Robot Framework for Goibibo.com.

2023-05-13 05:53 UTC, prateek1604 requested changes
@Subhajit908 Can you please check the comments and let me know if any help is required

2023-05-13 05:53 UTC, prateek1604 commented on Subhajit/Robot_Framework/Result/log.html
Please remove all log, report, result files from PR

2023-05-13 05:53 UTC, prateek1604 commented on Subhajit/Robot_Framework/Tests/Goibibo.robot
> +    Then User click on Flight Tab
Can we have a when statement in between....

2023-05-13 05:53 UTC, prateek1604 commented on Subhajit/Robot_Framework/Tests/Goibibo.robot
> +    Given User nevigate to Goibibo website
can you please correct the spelling of navigate

2023-05-13 05:53 UTC, prateek1604 commented on Subhajit/Robot_Framework/Resources/Goibibo_Keywords.robot
> +    open browser    https://www.goibibo.com/        chrome
This URL `https://www.goibibo.com/` can be different for different env's, So we should parametrize and parse it from configuration Env related files

2023-05-13 11:04 UTC, komalkapde approved these changes

2023-05-13 11:05 UTC, komalkapde approved these changes

2023-05-15 15:19 UTC, prateek1604 approved these changes

2023-05-15 15:29 UTC, pcube0608 approved these changes

2023-05-15 15:29 UTC, merged