RobotFrameworkAssignment
pcube0608/batch6 pull request #37
Opened 2023-05-13 19:43 UTC by santoshilondhe

Robot Framework Assignments added
Ready for your review!

2023-05-14 08:57 UTC, komalkapde approved these changes

2023-05-15 06:51 UTC, shriram3672 approved these changes
LGTM

2023-05-15 07:44 UTC, plaad-mdsol commented on RobotFramework/Tests/SouceDemo.robot
> +
Remove variable section if not req

2023-05-15 07:49 UTC, pcube0608 requested changes

2023-05-15 07:49 UTC, pcube0608 commented on RobotFramework/Configuration/Uat_Env.robot
> +${ENV}          Uat
ENV variable we can remove from here and parse as commandline argument
Please remove and commit from all env files

2023-05-15 07:49 UTC, pcube0608 commented on RobotFramework/Tests/SouceDemo.robot
> +*** Variables ***
Remove variable section

2023-05-15 07:49 UTC, pcube0608 commented on RobotFramework/Resources/Goibibo_Keywords.robot
> +
Pls remove all blank line from end of file

2023-05-15 07:49 UTC, pcube0608 commented on RobotFramework/Resources/SouceDemo_Keywords.robot
> +Login to the SouceDemo website
This line can be removed

2023-05-15 15:54 UTC, pcube0608 approved these changes

2023-05-15 15:58 UTC, merged