Create ESPN.PY
pcube0608/batch6 pull request #8
Opened 2023-05-03 07:25 UTC by Anshulsatle

please check it is good or not

2023-05-03 07:55 UTC, santoshilondhe approved these changes
LGTM

2023-05-03 09:13 UTC, berdedisha approved these changes
LGTM!

2023-05-04 02:43 UTC, pcube0608 requested changes

2023-05-04 02:43 UTC, pcube0608 commented on Anshul/ESPN.PY
> +
Please remove extra lines from here

2023-05-04 02:43 UTC, pcube0608 commented on Anshul/ESPN.PY
> +        global IPL1
Can we rename this object as driver ?

2023-05-04 02:43 UTC, pcube0608 commented on Anshul/ESPN.PY
> +        time.sleep(20)
Can we replace this hardcoded wait with explicit wait ?
Have we tried applying explicit wait ?
Please check if explicit wait works here.

2023-05-04 02:43 UTC, pcube0608 commented on Anshul/ESPN.PY
> +        # Ac1.move_to_element(ipl2021).click().perform()
Please remove commented code if not required

2023-05-04 02:43 UTC, pcube0608 commented on Anshul/ESPN.PY
> +        lastIpl=IPL1.find_element(By.XPATH,"//div[@class='ds-w-[288px] card scorecard']")
The class name contains white spaces and looks volatile.
Can we use contains in xpath to make it more generic

2023-05-04 02:52 UTC, pcube0608 commented on Anshul/ESPN.PY
> +        global IPL1
Done

2023-05-04 02:53 UTC, pcube0608 approved these changes
All changes are done. Thanks @Anshulsatle

2023-05-04 02:54 UTC, merged